### ISSUE TITLE
Pypi build has syntax error on py2

### ISSUE THREAD

**Issue by PikalaxALT** [nikdoof/python-ts3#15]
```
File "ts3/commands.py", line 79
def banadd(self, *, ip=None, name=None, uid=None, time=None, banreason=None):
                  ^
SyntaxError: invalid syntax
```

**Comment by mrandri19** [comment]
there is no function called banadd in this package nor a file called command.py so I guess that you defined it.
A variable in python cannot be named *, thats why it's giving you a syntax error

**Comment by PikalaxALT** [comment]
this error was raised when executing the command `pip install ts3`

**Comment by mrandri19** [comment]
then this is not the right repo :smile: , this is where you should be opening the issue: 
https://github.com/benediktschmitt/py-ts3

**Comment by nikdoof** [comment]
As above, closing :)
